language: node_js
node_js:
- '8.9.1'
branches:
  only:
  - master
script:
  - yarn run build
sudo: false
deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    all_branches: true
